### PR TITLE
Creation of user register and login endpoints

### PR DESCRIPTION
**Pull request by jeancheikh**
Created user endpoints:
/users/register:
 needs: email, name, password and role
/users/login
 needs: email and password

### CODE REVIEW

**Review by atoo — CHANGES_REQUESTED** [review]
Please fix all the issues pointed by Codacy: https://app.codacy.com/gh/BuildForSDGCohort2/Team-004-Backend/pullRequest?prid=6171324

**Review by jeancheikh — COMMENTED** [review]
Codacy Error Correction

**Review by Lenscorpx — APPROVED** [review]
LGTM

**Review by mzerbo98 — COMMENTED** [review]
@jeancheikh  We were supposed to have a single name field instead of firstname and lastname. Did we change ?

**Comment by atoo** [comment]
> @jeancheikh We were supposed to have a single name field instead of firstname and lastname. Did we change ?

I don't remember. Please stick on the approved schema.
@mzerbo98 you can reply the review by requesting change as well instead of approving.

**Review by mzerbo98 — CHANGES_REQUESTED** [review]
Could you replace firstName and lastName with name please ?

**Review by mzerbo98 — APPROVED** [review]

**Review by atoo — APPROVED** [review]
Approved based on the 2 previous approvals.

**Pull request merged**
