### PR TITLE
Courses stream publish

### LINKED ISSUE #7: Video streaming endpoint for not signed in user (Static)
Allow Guest(/Student/Teacher) user to stream the content of a hosted video.
GET /api/courses/{id}/stream

Note: As the endpoint for upload video is not yet ready, you can manually host a video file on the server for the purpose of working the endpoint. The goal here is to have the code to manage video streaming.

### LINKED ISSUE #15: Allow Student and Teacher to stream video
Allow Guest/Student/Teacher user to stream the content of a hosted video.
GET /api/courses/{id}/stream

Once issue https://github.com/BuildForSDGCohort2/Team-004-Backend/issues/6 is closed, please finalize issue https://github.com/BuildForSDGCohort2/Team-004-Backend/issues/7 by allowing Student and Teacher as weel.

### LINKED ISSUE #16: Count a video view
Count each request to GET /api/courses/{id}/stream as a video view.
Before sending the content, update the views count of the video.

### LINKED ISSUE #17: Publish new video for Teacher
Allow Teacher to publish a video
POST /courses

The teacher should provide as input: title, subject, level, country, description, language, url and thumbnail_url.

Feel free to add any restriction you think necessary as allowed file types, max file size etc and document them https://docs.google.com/document/d/1Yj2bqFhWKQj5pcH84dRO312KQz2WlcrZjyvBf2reB7Q/edit

The response should include the course id.

### PR DESCRIPTION
**Pull request by mzerbo98**
Added Video publish, streaming and view counts.
The videoUrl attriute should be a relative path to the video (starting from project root where app.js is)
For example : "/uploads/videos/21092020.mp4" 
closes #16, closes #17, closes #7, closes #15

### CODE REVIEW

**Review by jeancheikh — DISMISSED** [review]
Good

**Review by atoo — CHANGES_REQUESTED** [review]
Please fix Codacy issues before other review https://app.codacy.com/gh/BuildForSDGCohort2/Team-004-Backend/pullRequest?prid=6212691

**Comment by mzerbo98** [comment]
Corrected edacy errors

**Review by Lenscorpx — APPROVED** [review]

**Review by jeancheikh — APPROVED** [review]
Looks good to me

**Review by atoo — APPROVED** [review]
Approved based on the 2 other approvals.

**Pull request merged**
