### PR TITLE
TEST

### PR DESCRIPTION
**Pull request by jeancheikh**
Hi Guy!

Check this is for /api/users/login and /api/users/register features

### CODE REVIEW

**Comment by ucheuzor** [comment]
Try to add team members for review

**Review by atoo — CHANGES_REQUESTED** [review]
Please remove node_modules directory and any directory your are not working in. They will be downloaded by each one locally. Only include the directories/files you work in, and settings/configs files which will allow other to download the necessary node modules. 

Also please don't clone and work on the master branch, but the develop instead.

**Review by mzerbo98 — CHANGES_REQUESTED** [review]
I agree with @atoo , there is no need for node_modules in the repository we'll just npm i. In fact, I can't even see the server files because of the many depedencies

**Review by Lenscorpx — CHANGES_REQUESTED** [review]
this commit is too large for a review! I think it's because you put node_modules on your git!

**Pull request closed without merging**
